// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "miroslav.safaric@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cache/{domain}": {
            "get": {
                "description": "\"Route for checking if cache exists and returing value of it\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Cache get route",
                "operationId": "caches.GET",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain",
                        "name": "domain",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseGET"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseGET"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseGET"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseGET"
                        }
                    }
                }
            },
            "delete": {
                "description": "\"Route that tries to delete cahce folder for given domain\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Cache delete route",
                "operationId": "caches.DELETE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain",
                        "name": "domain",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseDELETE"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseDELETE"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseDELETE"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.CacheEndpointResponseDELETE"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CacheEndpointResponseDELETE": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "www.domain.tld"
                },
                "msg": {
                    "type": "string",
                    "example": "cache_folder_not_found"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "models.CacheEndpointResponseGET": {
            "type": "object",
            "properties": {
                "cacheSize": {
                    "type": "number",
                    "example": 1024
                },
                "domain": {
                    "type": "string",
                    "example": "www.domain.tld"
                },
                "msg": {
                    "type": "string",
                    "example": "cache_folder_not_found"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "localhost:5000",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "nginx-restapi-cache-purge",
	Description: "A simple API for deleting Nginx cache via HTTP calls. It enables you to get status and size of cache for certian domain and also delete cache for that domain",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
