package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	_ "https://github.com/mirsafari/nginx-restapi-cache-purge/api/v1" // docs is generated by Swag CLI, you have to import it.
)

// @title nginx-restapicache-purge
// @version 0.1
// @description Repository containing simple API for deleting Nginx cache via HTTP calls

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath /v1

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// Setup global variables
var router = gin.Default()
var cachePath string
var APIKey string

// Run will start the server
func main() {

	flag.StringVar(&cachePath, "cache-path", os.Getenv("NGINX_CACHE_DIR"), "Path to folder containing Nginx cahce")
	flag.StringVar(&APIKey, "api-key", os.Getenv("APIKEY"), "API Key used to access this service (min. 16 chars)")
	flag.Parse()

	// Simple validation for input flags
	if len(cachePath) == 0 && len(APIKey) < 16 {
		fmt.Println("Please provide valid API key and Nginx cache dir")
		os.Exit(1)
	}

	// getRoutes will create our routes of our entire application
	// this way every group of routes can be defined in their own file
	// so this one won't be so messy
	getRoutes()

	// Allow gin to return 405 if method is not defined in router
	router.HandleMethodNotAllowed = true

	url := ginSwagger.URL("http://localhost:5000/v1/api/doc.json") // The url pointing to API definition
	router.GET("/v1/api/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	// Start server
	router.Run(":5000")
}
