basePath: /
host: localhost:5000
info:
  contact:
    email: miroslav.safaric@gmail.com
  description: A simple API for deleting Nginx cache via HTTP calls. It enables you
    to get status and size of cache for certian domain and also delete cache for that
    domain
  title: nginx-restapi-cache-purge
  version: 0.0.1
paths: {}
swagger: "2.0"
