package handlers

import (
	"github.com/gin-gonic/gin"
	_ "github.com/mirsafari/nginx-restapi-cache-purge/api/v1" // docs is generated by Swag CLI, you have to import it.
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// Swagger webUI
func AddSwaggerRoute(rg *gin.RouterGroup) {
	swagger := rg.Group("/api")

	url := ginSwagger.URL("http://localhost:5000/v1/api/doc.json") // The url pointing to API definition

	swagger.GET("/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url), func(c *gin.Context) {
	})
}
